[build]
cmd = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
