/**
 * 常量和类型导出
 */

// 类型导出
export type {
  DecisionType,
  DecisionStyle,
  ImportanceLevel,
  ImportanceStyle,
  DimensionConfig,
  PriceLevelType,
  PriceLevelStyle
} from './styles';

// 函数导出
export {
  getDecisionStyle,
  getImportanceStyle,
  getPriceLevelStyle
} from './styles';

// 常量导出
export {
  STOCK_NAME_MAP,
  STOCK_TOTAL_SHARES_MAP,
  DEFAULT_TOTAL_SHARES,
  TRADING_RATIO_CONFIG,
  QUANT_SCORE_THRESHOLDS,
  DIMENSION_WEIGHTS,
  FIBONACCI_LEVELS,
  FIBONACCI_EXTENSIONS,
  FIBONACCI_SCORE_CONFIG,
  MA_PERIODS,
  MACD_CONFIG,
  RSI_CONFIG,
  SUPPORT_RESISTANCE_CONFIG,
  RISK_REWARD_SCORE_CONFIG,
  AVG_DAILY_VOLUME,
  VOLUME_RATIO_CONFIG,
  STORAGE_KEY_PREFIX,
  getStorageKey,
  API_TIMEOUT_CONFIG,
  MAX_API_LOGS
} from './config';

// 样式常量导出
export {
  DIMENSIONS,
  GLASS_CARD_CLASS,
  BASE_CARD_CLASS,
  HIGHLIGHT_CARD_CLASS,
  PRIMARY_BUTTON_CLASS,
  SECONDARY_BUTTON_CLASS,
  SUCCESS_BUTTON_CLASS,
  DANGER_BUTTON_CLASS,
  GRID_6_CLASS,
  GRID_3_CLASS,
  GRID_2_RESPONSIVE_CLASS,
  TITLE_CLASS,
  SUBTITLE_CLASS,
  PRIMARY_VALUE_CLASS,
  SECONDARY_VALUE_CLASS,
  MARGIN_BOTTOM_CLASS,
  MARGIN_BOTTOM_LARGE_CLASS,
  PADDING_CLASS,
  PADDING_LARGE_CLASS
} from './styles';
